#include <iostream>
#include <cstring>
#include <fstream>
#include "src/cxxopts.hpp"
#include "src/chromo_phaser.h"
using namespace std;
float T1;
float T2;
int P_ENSURE_BLOCK;
int P_ENSURE_SIDE;
bool ONLY_CHILD;
bool XY;
bool IS_MALE;
int BND_RANGE;

//TODO this is a tmp
int main(int argc, char *argv[]) {
    cxxopts::Options options("pedhap", "pedigree hap");
    options.add_options()
            ("vcf", "operate: check or solve", cxxopts::value<std::string>())
            ("ped", "Pedigree file generated by python file", cxxopts::value<std::string>())
            ("out", "Output phased vcf file", cxxopts::value<std::string>())
            ("t1", "Block Merge Support site count for hete", cxxopts::value<float>()->default_value("5"))
            ("t2", "Block Merge Support site count for homo", cxxopts::value<float>()->default_value("8"))
            ("oc", "Only child with be phased", cxxopts::value<bool>()->default_value("1"))
            ("bnd_range", "Phasing bnd position range", cxxopts::value<int>()->default_value("100"))
            ("verbose", "Verbose output", cxxopts::value<bool>()->default_value("false"))
            ("xy", "Whether phasing sexual chromosome", cxxopts::value<bool>()->default_value("false"))
            ("sexual", "Sexual of child", cxxopts::value<std::string>())
            ("help", "Print usage");
    auto result = options.parse(argc, argv);
    if (result.count("help")) {
        std::cout << options.help() << std::endl;
        exit(0);
    }
    auto pedFileName = result["ped"].as<std::string>();
    auto vcfFileName = result["vcf"].as<std::string>();
    auto vcfOut = result["out"].as<std::string>();
    XY = result["xy"].as<bool>();
    T1 = result["t1"].as<float>();
    T2 = result["t2"].as<float>();
    BND_RANGE = result["bnd_range"].as<int>();
    ONLY_CHILD = result["oc"].as<bool>();
    auto *phaser = new Phaser(vcfFileName, vcfOut);

    std::ifstream ped(pedFileName);
    std::string fa, mo, ch, gender;
    std::vector<std::string> trio;
    bool flag = true;
    while (ped >> ch >> fa >> mo) {
        if(ch == "#" && flag) {
            flag = false;
        }
        trio.push_back(ch);
        trio.push_back(fa);
        trio.push_back(mo);
        trio.push_back(gender);
        if(flag)
            phaser->up_to_down.push_back(trio);
        else
            phaser->down_to_up.push_back(trio);
        trio.clear();
    }
    phaser->phasing();
    delete phaser;
}